### ISSUE TITLE
Spurious `Set`?

### ISSUE THREAD

**Issue by markuspf** [gap-packages/datastructures#105]
https://github.com/gap-packages/datastructures/blob/1b2cbd9bd4c8163e4a879b20f140fd271b09b057/gap/hashfunctions.gi#L20

@ChrisJefferson I suspect this use of `Set` as the last argument for the hash is not intentional?

**Comment by ChrisJefferson** [comment]
I think it is --  Orbits(G) seems to return a list of lists which isn't ordered, so I have to order both each orbits, and the orbits as a list, so the result is the same whenever G is the same.

Actually, I could (and maybe should) be sorting each orbit, and then sorting the resulting list, but we know there are no duplicates, so Set does just as well.

**Comment by ChrisJefferson** [comment]
Little example:
```
gap> g := Group((1,2),(2,3,4,5));;
gap> h := g^(1,5,2,4,3);;
gap> g = h;
true
gap> Orbits(g) = Orbits(h);
false
gap> Set(Orbits(g) = Set(Orbits(g);
false
gap> Set(Orbits(g), Set) = Set(Orbits(g), Set);
true
```

**Comment by markuspf** [comment]
Yes, I parsed the parantheses wrong when I saw this code in a meeting with a student nd just left the issue here to not forget. Thanks!
