### ISSUE TITLE
Tests fail with all packages loaded in GAP master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/datastructures#113]
See e.g. https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/497783571

```
########> Diff in /home/gap/inst/gap-master/pkg/datastructures-0.2.3/tst/slice\
.tst:15
# Input is:
ViewString(s);
# Expected output:
"<slice size=3>"
# But found:
"[ 3,\<\> 2,\<\> 4 ]"
########
```

**Comment by ChrisJefferson** [comment]
I can't reproduce this. Is it still there?

**Comment by alex-konovalov** [comment]
Yes:
- https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-staging/jobs/508558222
- https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/508684667

Did you load all packages?

**Comment by ChrisJefferson** [comment]
I called LoadAllPackages(), but of course there are a bunch of packages I can't load.

**Comment by alex-konovalov** [comment]
I can get this on kovacs. `ApplicableMethod` points to the library method in `lib/list.gi` (from line 328). Some bisection points that it is triggered by the FR package. None of the FR dependencies trigger this.

**Comment by alex-konovalov** [comment]
P.S. Note that applicable method is

```
InstallMethod( ViewString, "call ViewString and incorporate hints",
  [ IsList and IsFinite],
```

what may be relevant to #114.

**Comment by ChrisJefferson** [comment]
thanks, fixed

**Comment by alex-konovalov** [comment]
Thanks! Can't see where, though. A link to the fixing commit or PR would be useful.
