### ISSUE TITLE
Pairing heap: rewrite in C? Or else drop it?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/datastructures#35]
Current test results on my machine:
```
testing: tst/binaryheap.tst
      57 msec for binaryheap.tst
testing: tst/pairinghap.tst
    6113 msec for pairingheap.tst
...
```
So the pairing heap is more than 100 times slower than the binary heap in this microbenchmarks. But a lot of that may come from the overhead of GAP code over C. To give it a fair chance, we should rewrite it in C.

If that doesn't help, or if we can't be bothered to try it, we might be better of removing it, because at least right now, I wouldn't want to recommend it to anybody...

**Comment by fingolfin** [comment]
(To be clear: That is not meant as a criticism of pairing heaps in general, nor of the current implementation, which looks reasonable; it's simply so that pure GAP code won't stand a chance against a C implementation for this kind of thing)

**Comment by markuspf** [comment]
Now on my machine

```
testing: /home/makx/dev/gap/pkg/datastructures/tst/binaryheap.tst
     110 msec for binaryheap.tst  
testing: /home/makx/dev/gap/pkg/datastructures/tst/pairingheap.tst
     203 msec for pairingheap.tst   
```

Which is not too shabby considering its a pure GAP implementation and doesn't play any array-storage tricks.

**Comment by fingolfin** [comment]
Now that we have implemented the merging in C, the timings are even closer, and this issue can definitely be closed.
