### ISSUE TITLE
IsPlistQueueRep is buggy, losses data when resizing

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/datastructures#50]
Example:
```
gap> q := PlistQueue();
<queue with 0/64 entries>
gap> for i in [1..63] do PushFront(q,i); od;
gap> q;
<queue with 63/64 entries>
gap> PushFront(q,64);
gap> q;
<queue with 2/128 entries>
```
Part of the problem seems to be that `PlistQueueExpand` does not (re)set the head of the queue. The other part is that some code calling `PlistQueueExpand` seems to make implicit assumptions about how it works, which simply are not met here. E.g. in `PlistQueuePushFront`:
```gap
      PlistQueueExpand(queue);
      head := queue![QCAPACITY];   # <-- why????
      queue![QDATA][head] := el;
      queue![QHEAD] := head;
```

I have not tested if the original code from GAP's `lib/queue.g` works correctly. If it does, we could start over using that. Otherwise, I'd just drop that code, and rewrite it from scratch in C. That should be easier than trying to reverse engineer this undocumented code.

**Comment by markuspf** [comment]
Addressed in #59
