### ISSUE TITLE
Non-Termination of HashTable look up on certain conditions (HPC-GAP).

### ISSUE THREAD

**Issue by Alasdair-Macindoe** [gap-packages/datastructures#83]
Hi,
Under certain conditions it seems that HashTable will not return a value moreover it does not seem to even terminate. 

# Input
```
gap> a := HashMap();;
gap> a[Transformation([4, 1, 4, 1])] := 1;
1
gap> a[Transformation([1, 1, 4, 1])] := 1;
1
gap> a[Transformation([3, 3, 4, 3])] := 1;
1
gap> a[Transformation([1, 1, 4, 4])] := 1;
1
gap> a[Transformation([4, 4, 4, 2])] := 1;
1
gap> a[Transformation([1, 1, 1])] := 1;   
1
gap> a[Transformation([2, 2, 4, 2])] := 1; 
1
gap> a[Transformation([1, 4, 4, 1])] := 1;
1
gap> a[Transformation([3, 1, 1, 3])] := 1;
1
gap> a[Transformation([2, 2, 3, 3])] := 1;
1
gap> a[Transformation([2, 2, 3, 2])] := 1;
1
gap> a[Transformation([3, 3, 1, 3])];
```

The final line will never return a value. 
Most interestingly is that if you omit any of the values into the HashMap then the expected behaviour occurs (fail is returned). Additionally for some other Transformations it will work:

If `a[Transformation([2, 2, 3, 2])] := 1;` is replaced with `a[Transformation([1, 2, 3, 4])] := 1;` then the expected behaviour occurs. Surprisingly if `a[Transformation([2, 2, 3, 2])] := 1;`  is replaced with `a[Transformation([2, 2, 3, 4)] := 1;`  it still breaks.

*Note:* This has not been tested on GAP yet.

**Comment by markuspf** [comment]
fwiw this happens in GAP, too.
