### ISSUE TITLE
Remove use of obsolete SHALLOW_SIZE

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/datastructures#87]
There is one use of `SHALLOW_SIZE`. It is obsolete and should be replaced by `SIZE_OBJ`, see

https://github.com/gap-system/gap/blob/262e53d0513b507ad187278f28557245e8345cd4/lib/obsolete.gd#L595

**Comment by markuspf** [comment]
`SHALLOW_SIZE` is not used by datastructures.
