### ISSUE TITLE
`atomic_ops.h` not found, CPPFLAGS not set correctly?

### ISSUE THREAD

**Issue by markuspf** [gap-packages/datastructures#88]
With a checkout from the master branch the usual `sh autogen.sh ; configure ; make` does not work if GAP is configured as HPC-GAP

**Comment by fingolfin** [comment]
I expect most packages using the semi-standard autoconf+automake build system to suffer from that or similar (though I haven't tested recently).

My plan always was to prepare a patch for all these packages once GAP 4.9 is more or less ready, but to be frank, it's very hard to find the time and (more importantly) motivation for that right now. But I did preliminary work on this for the `io` package, which could conceivable be ported to other packages (I just have not tested it extensively), see https://github.com/gap-packages/io/commit/d1491f4c0ef095da800b9aeb573459c3d75bf0e4

Overall, I believe that most packages would actually be better of switching from autoconf+automake to a simpler gac based build system which doesn't suffer from such issues, see https://github.com/gap-packages/orb/pull/38 -- the `datastructure` package should be a prime candidate for this, too.

**Comment by markuspf** [comment]
This is now invalid (and I think `datastructures` is currently incompatible with HPC-GAP by merging #90).
