### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by oysteins** [gap-packages/datastructures#92]
As far as I can see, there are no instructions on how to compile the C code of this package, neither in the README file, the manual or anywhere else.

I tried the following commands (replacing "GAPROOT" with the directory of my GAP installation):
```sh
$ ./autogen.sh
$ ./configure --with-gaproot=GAPROOT
$ make
```
This seems to work, but it would have been nice if I could be told what to do by the package's documentation instead of having to guess.

Furthermore, I think it would be a good idea to document which tools are required to build the package. One of the required tools is, apparently, GNU Libtool. When trying the above commands without libtool installed, I got the following somewhat cryptic error message from `./autogen.sh`:
```
Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:6:   its definition is in aclocal's search path.
```
Again, I was able to guess what I needed to do (that is, install libtool), but it was not entirely obvious.

**Comment by markuspf** [comment]
How do you build gap without libtool?

**Comment by oysteins** [comment]
What I usually do to build gap is to download the latest release, and run `./configure` and `make` (as `INSTALL.md` tells me to). I don't think libtool should be required for this, and in any case I have never run into any problems when doing this without having libtool installed.

I notice that GAP's `README.md` says that in order to build the latest development version from the git repository, I additionally need to run `./autogen.sh` first, and I need to have libtool installed. Right now, I tried to uninstall libtool, then clone the git repository of GAP and run `./autogen.sh`, `./configure` and `make`, just to see when and how it fails. But it didn't. The whole build process went perfectly fine, as far as I could tell.

So although GAP's documentation says that I need libtool if (and presumably only if) I want to compile a development version, I'm not able to find any way to make the build fail when libtool is not installed.

Aside from this, do you assume that anyone who wants to compile the datastructures package has installed GAP from source, as opposed to using a precompiled GAP (for instance from the operating system's package manager)?

**Comment by markuspf** [comment]
Can you have a look at the packages documentation now: https://gap-packages.github.io/datastructures/doc/chap2.html ?

Note that compilation has changed since you submitted your issue, and `autogen.sh` is not needed (or present) anymore.

**Comment by oysteins** [comment]
This looks good.

One comment: The following sentence is a little strange.
> To install a released version of this package, either extract the package's archive file into GAP's pkg folder.

I think that either the word "either" should not be there, or there should be an "or".

**Comment by markuspf** [comment]
Thanks. For future reference, you can just submit a pull-request by editing the documentation on github (in this case in `doc/install.xml`), if you want.
